### ISSUE TITLE
[META] Better log messages

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/rpdf#78]
# Issues

- [ ] Log messages are currently lacking some information, e.g., https://github.com/jeertmans/rpdf/blob/11da7a97b9f4083b72ffa42066f9f17478eee064/src/cli/annotations.rs#L171
does not indicate the page id, which makes it harder to debug;
- [ ] All messages (log and error) should end with a ".";
- [ ] The following https://github.com/jeertmans/rpdf/blob/11da7a97b9f4083b72ffa42066f9f17478eee064/src/cli/annotations.rs#L205-L216
should probably use [`slice::join`](https://doc.rust-lang.org/std/primitive.slice.html#method.join).

# How to fix

Fixes are pretty easy, feel free to submit a pull request!

**Comment by Brijeshthummar02** [comment]
hello there, @jeertmans i would work on this, assign me the task.

**Comment by jeertmans** [comment]
Hi @Brijeshthummar02! I am not assigning tasks because it will just refrain other people from contributing too.

This issue can be addressed with up to 3 different PRs, and I would be happy to review any contribution you might propose :)

**Comment by Brijeshthummar02** [comment]
Share feedback for current pull request, and if it's fine than please do me a favor merge it in oct 1-2 when hacktoberfest starts so that i can claim merge request.
